// Generated by CoffeeScript 1.9.3
(function() {
  var WebSocket, ws;

  WebSocket = require('ws');

  ws = new WebSocket("ws://yo-ren.com:7070/theHooker");

  ws.on('open', function() {
    ws.send('something');
    return ws.on('message', function(data, flags) {
      var msg;
      msg = JSON.parse(data);
      console.log('msg', msg);
      return console.log(data);
    });
  });

}).call(this);
