// Generated by CoffeeScript 1.9.3
(function() {
  var WebSocketServer, WebhookServer, server, wss;

  WebhookServer = require('simplewebhook');

  WebSocketServer = require('ws').Server;

  wss = new WebSocketServer({
    port: 7070
  });

  server = WebhookServer({
    serverType: 'gitlab'
  });

  wss.on('connection', function(ws) {
    server.addHook({
      link: '/theHooker',
      event: '*',
      exec: 'time',
      options: {
        encoding: 'utf8'
      },
      handler: function(error, stdout, stderr) {
        ws.send('wtf');
        console.log('Request body :', this.request.body);
        console.log('List command: ', stdout);
        this.response.send('Hello');
      }
    });
    ws.on('message', function(message) {
      return console.log('received: %s', message);
    });
    return ws.send('Welcome to Webhook Proxy ...');
  });

  server.listen(3333);

}).call(this);
