// Generated by CoffeeScript 1.10.0
(function() {
  var WebSocketServer, WebhookServer, server, wss;

  WebhookServer = require('simplewebhook');

  WebSocketServer = require('ws').Server;

  wss = new WebSocketServer({
    port: 7070
  });

  server = WebhookServer({
    serverType: 'gitlab'
  });

  wss.broadcast = function(data) {
    return wss.clients.forEach(function(client) {
      return client.send(data);
    });
  };

  wss.on('connection', function(ws) {
    ws.on('message', function(message) {
      return console.log('received: %s', message);
    });
    return ws.send(JSON.stringify({
      msg: 'Welcome to Webhook Proxy ...'
    }));
  });

  server.addHook({
    link: '/theHooker',
    event: '*',
    exec: 'time',
    options: {
      encoding: 'utf8'
    },
    handler: function(error, stdout, stderr) {
      wss.broadcast(JSON.stringify(this.request.body));
      console.log('Request body :', this.request.body);
      console.log('List command: ', stdout);
      this.response.send('Hello');
    }
  });

  server.listen(3333);

}).call(this);
